# config.yaml (全局配置文件)

system:
  # 是否开启本地代理穿透 (国内开发必开，如果你部署到海外服务器，把这个改成 false)
  use_proxy: true
  proxy_url: "http://127.0.0.1:10809"
  debug: true

database:
  # InfluxDB 的连接配置
  url: "http://localhost:8086"
  token: "my-super-secret-auth-token-for-kline"
  org: "kline_org"
  bucket: "kline_bucket"

server:
  host: "0.0.0.0"
  port: 8000