services:
  # 服务主体：Web 和采集服务
  kline-app:
    build: .
    container_name: kline_engine
    ports:
      - "8089:8000"
    depends_on:
      - influxdb
      - redis
    volumes:
      #显式挂载 config.yaml 进行配置
      - ./config.yaml:/app/config.yaml
    restart: always

  # 时序数据库
  influxdb:
    image: influxdb:2.7-alpine
    container_name: kline_influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345
      - DOCKER_INFLUXDB_INIT_ORG=kline_org
      - DOCKER_INFLUXDB_INIT_BUCKET=kline_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token-for-kline
    volumes:
      # 时序数据库持久化
      - influxdb-data:/var/lib/influxdb2
    restart: always

  # Redis 消息总线
  redis:
    image: redis:7-alpine
    container_name: kline_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # 开启 AOF 持久化
    volumes:
      # Redis 数据持久化
      - redis-data:/data
    restart: always

volumes:
  influxdb-data:
  redis-data: